### ISSUE TITLE
Generating _Definitions.xml files

### ISSUE THREAD

**Issue by jayrulez** [UltravioletFramework/ultraviolet#147]
@tlgkccampbell How did you generate the _Definitions.xml files for native bindings?

**Comment by tlgkccampbell** [comment]
They weren't generated, I wrote them by hand.

**Comment by jayrulez** [comment]
I would like to publish nuget packages for the .NET 6 update. I will also update the templates and samples accordingly.

I have the changes on this branch https://github.com/jayrulez/ultraviolet/commits/rename2 (Note, this supersedes the changes from the PR). 

I already have all the nuget packages built locally. I just need an api key to publish them.

Android is important to me so I'd also like to understand the need for the modifications to SDL here:
https://github.com/tlgkccampbell/ultraviolet-sdl2/commit/53e4146d4555e0e607096151de3e01d37bc75ddb

Is it feasible to use stock SDL?

If you don't mind, please add me on Discord jayrulez#1364 as I may have some more questions.
